name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
    
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up .NET v6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # SDK Version to use
      # Step 3
      - name: Build Application
        run: dotnet build src
      # Step 4
      - name: Publish Application
        run: dotnet publish src -o app

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name dotnet-hello-world \
            --deployment-group-name AppDeploymentGroup1 \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
