# Learn more about the syntax here:
# https://docs.github.com/en/early-access/github/save-time-with-slash-commands/syntax-for-user-defined-slash-commands
---
trigger: meeting_notes
title: Meeting Notes
surfaces:
   - issue
description: Spawn up a template for notes. Great for multitasking SE's!

# Each command has one or more steps. You can add up to 25 steps.
steps:
  # This displays a form with a dropdown, text input, and markdown editor.
  - type: form
    style: modal
    body:
      - type: input
        attributes:
          label: Title
          placeholder: POC Kick-Off Call...
      - type: input
        attributes:
          label: Attendees
          placeholder: @octocat, @mona, customer1, customer2...
      - type: textarea
        attributes:
          label: Notes
          placeholder: Organize this how you want
          value: - 
      - type: textarea
        attributes:
          label: NextSteps
          placeholder: Organize this how you want
          value: |
          @{{ command.user.login }}
          - [ ]
          @Rep
          - [ ]
      - type: textarea
        attributes:
          label: See available commands
          value: |
          {{ data }}
          
          -- Break --
          
          {{ command }}
      - type: markdown
        attributes:
          text: - [ ] TEST
      - type: fill
        template: |-
          Thank you for creating a slash command! See
          Here is the data you provided: {{data}}
          And here is some information about the command: {{command}}

          ### [_Customer_] - {{ data.Title }}
          **Date:** [_Date_]

          **Attendees:** {{ data.Attendees }}

          **Notes:**

          {{ data.Notes }}

          **Next Steps**

          {{ data.NextSteps }}
